services:

  postgresql_hexagonal:
    image: postgres:15.3
    container_name: db_planilla
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Password2026
      POSTGRES_DB: db_planilla
    ports:
      - "1502:5432"
    volumes:
      - D:\Ejercicios\NET\volumenes:/var/lib/postgresql/data
    networks:
      - api-planilla-network

networks:
  api-planilla-network:
    driver: bridge