<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Papa.Planilla.Domain\Papa.Planilla.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Common\Contants\" />
    <Folder Include="Common\Abstractions\" />
    <Folder Include="Features\Contrato\DTO\" />
    <Folder Include="Features\Planilla\DTO\" />
    <Folder Include="Features\Planilla\Ports\" />
    <Folder Include="Features\Planilla\UseCases\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.7" />
  </ItemGroup>

</Project>
