// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Papa.Planilla.Infraestructure.Configuration.Repositories.Context;

#nullable disable

namespace Papa.Planilla.Infraestructure.Migrations
{
    [DbContext(typeof(PlanillaDbContext))]
    [Migration("20260611221844_CambiosPendientesPlanilla")]
    partial class CambiosPendientesPlanilla
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("planilla")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Papa.Planilla.Domain.Entities.Cargo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UsuarioActualizacion")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioCreacion")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("cargos", "planilla");
                });

            modelBuilder.Entity("Papa.Planilla.Domain.Entities.Contrato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CargoId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<string>("EstadoContrato")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado_contrato");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_inicio");

                    b.Property<Guid>("TrabajadorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UnidadOrganicaId")
                        .HasColumnType("uuid");

                    b.Property<int>("UsuarioActualizacion")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioCreacion")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CargoId");

                    b.HasIndex("EstadoContrato");

                    b.HasIndex("FechaFin");

                    b.HasIndex("FechaInicio");

                    b.HasIndex("TrabajadorId");

                    b.HasIndex("UnidadOrganicaId");

                    b.ToTable("contratos", "planilla");
                });

            modelBuilder.Entity("Papa.Planilla.Domain.Entities.Planilla", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Anio")
                        .HasColumnType("integer")
                        .HasColumnName("anio_planilla");

                    b.Property<Guid>("ContratoId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<string>("EstadoPlanilla")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado_planilla");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Mes")
                        .HasColumnType("integer")
                        .HasColumnName("mes_planilla");

                    b.Property<Guid>("TrabajadorId")
                        .HasColumnType("uuid");

                    b.Property<int>("UsuarioActualizacion")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioCreacion")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Anio");

                    b.HasIndex("ContratoId");

                    b.HasIndex("EstadoPlanilla");

                    b.HasIndex("Mes");

                    b.HasIndex("TrabajadorId");

                    b.ToTable("planillas", "planilla");
                });

            modelBuilder.Entity("Papa.Planilla.Domain.Entities.Trabajador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApellidoMaterno")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("apellido_materno");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("apellido_paterno");

                    b.Property<string>("Correo")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("correo");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombres");

                    b.Property<int>("UsuarioActualizacion")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioCreacion")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("trabajadores", "planilla");
                });

            modelBuilder.Entity("Papa.Planilla.Domain.Entities.UnidadOrganica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(350)
                        .HasColumnType("character varying(350)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UsuarioActualizacion")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioCreacion")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("unidades_organicas", "planilla");
                });

            modelBuilder.Entity("Papa.Planilla.Domain.Entities.Contrato", b =>
                {
                    b.HasOne("Papa.Planilla.Domain.Entities.Cargo", "Cargo")
                        .WithMany("Contratos")
                        .HasForeignKey("CargoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Papa.Planilla.Domain.Entities.Trabajador", "Trabajador")
                        .WithMany("Contratos")
                        .HasForeignKey("TrabajadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Papa.Planilla.Domain.Entities.UnidadOrganica", "UnidadOrganica")
                        .WithMany("Contratos")
                        .HasForeignKey("UnidadOrganicaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Papa.Planilla.Domain.ValueObjects.Importe", "Sueldo", b1 =>
                        {
                            b1.Property<Guid>("ContratoId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Moneda")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("sueldo_moneda");

                            b1.Property<decimal>("Monto")
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("sueldo_monto");

                            b1.HasKey("ContratoId");

                            b1.ToTable("contratos", "planilla");

                            b1.WithOwner()
                                .HasForeignKey("ContratoId");
                        });

                    b.Navigation("Cargo");

                    b.Navigation("Sueldo")
                        .IsRequired();

                    b.Navigation("Trabajador");

                    b.Navigation("UnidadOrganica");
                });

            modelBuilder.Entity("Papa.Planilla.Domain.Entities.Planilla", b =>
                {
                    b.HasOne("Papa.Planilla.Domain.Entities.Contrato", "Contrato")
                        .WithMany("Planillas")
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Papa.Planilla.Domain.Entities.Trabajador", "Trabajador")
                        .WithMany("Planillas")
                        .HasForeignKey("TrabajadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Papa.Planilla.Domain.ValueObjects.Importe", "SueldoBasico", b1 =>
                        {
                            b1.Property<Guid>("PlanillaId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Moneda")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("sueldo_basico_moneda");

                            b1.Property<decimal>("Monto")
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("sueldo_basico_monto");

                            b1.HasKey("PlanillaId");

                            b1.ToTable("planillas", "planilla");

                            b1.WithOwner()
                                .HasForeignKey("PlanillaId");
                        });

                    b.OwnsOne("Papa.Planilla.Domain.ValueObjects.Importe", "TotalDescuentos", b1 =>
                        {
                            b1.Property<Guid>("PlanillaId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Moneda")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("total_descuento_moneda");

                            b1.Property<decimal>("Monto")
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("total_descuento_monto");

                            b1.HasKey("PlanillaId");

                            b1.ToTable("planillas", "planilla");

                            b1.WithOwner()
                                .HasForeignKey("PlanillaId");
                        });

                    b.OwnsOne("Papa.Planilla.Domain.ValueObjects.Importe", "TotalIngresos", b1 =>
                        {
                            b1.Property<Guid>("PlanillaId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Moneda")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("total_ingresos_moneda");

                            b1.Property<decimal>("Monto")
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("total_ingresos_monto");

                            b1.HasKey("PlanillaId");

                            b1.ToTable("planillas", "planilla");

                            b1.WithOwner()
                                .HasForeignKey("PlanillaId");
                        });

                    b.Navigation("Contrato");

                    b.Navigation("SueldoBasico")
                        .IsRequired();

                    b.Navigation("TotalDescuentos")
                        .IsRequired();

                    b.Navigation("TotalIngresos")
                        .IsRequired();

                    b.Navigation("Trabajador");
                });

            modelBuilder.Entity("Papa.Planilla.Domain.Entities.Trabajador", b =>
                {
                    b.OwnsOne("Papa.Planilla.Domain.ValueObjects.DocumentoIdentidad", "DocumentoIdentidad", b1 =>
                        {
                            b1.Property<Guid>("TrabajadorId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("numero_documento");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasMaxLength(12)
                                .HasColumnType("character varying(12)")
                                .HasColumnName("tipo_documento");

                            b1.HasKey("TrabajadorId");

                            b1.HasIndex("Tipo", "Numero")
                                .IsUnique();

                            b1.ToTable("trabajadores", "planilla");

                            b1.WithOwner()
                                .HasForeignKey("TrabajadorId");
                        });

                    b.OwnsOne("Papa.Planilla.Domain.ValueObjects.NumeroCelular", "NumeroCelular", b1 =>
                        {
                            b1.Property<Guid>("TrabajadorId")
                                .HasColumnType("uuid");

                            b1.Property<string>("CodigoPais")
                                .IsRequired()
                                .HasMaxLength(5)
                                .HasColumnType("character varying(5)")
                                .HasColumnName("celular_codigo_pais");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("celular_numero");

                            b1.HasKey("TrabajadorId");

                            b1.HasIndex("CodigoPais", "Numero")
                                .IsUnique();

                            b1.ToTable("trabajadores", "planilla");

                            b1.WithOwner()
                                .HasForeignKey("TrabajadorId");
                        });

                    b.Navigation("DocumentoIdentidad")
                        .IsRequired();

                    b.Navigation("NumeroCelular")
                        .IsRequired();
                });

            modelBuilder.Entity("Papa.Planilla.Domain.Entities.UnidadOrganica", b =>
                {
                    b.OwnsOne("Papa.Planilla.Domain.ValueObjects.CodigoPresupuestal", "CodigoPresupuestal", b1 =>
                        {
                            b1.Property<Guid>("UnidadOrganicaId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Codigo")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("codigo_presupuestal");

                            b1.Property<string>("Descripcion")
                                .IsRequired()
                                .HasMaxLength(250)
                                .HasColumnType("character varying(250)")
                                .HasColumnName("codigo_presupuestal_descripcion");

                            b1.HasKey("UnidadOrganicaId");

                            b1.HasIndex("Codigo", "Descripcion")
                                .IsUnique();

                            b1.ToTable("unidades_organicas", "planilla");

                            b1.WithOwner()
                                .HasForeignKey("UnidadOrganicaId");
                        });

                    b.Navigation("CodigoPresupuestal")
                        .IsRequired();
                });

            modelBuilder.Entity("Papa.Planilla.Domain.Entities.Cargo", b =>
                {
                    b.Navigation("Contratos");
                });

            modelBuilder.Entity("Papa.Planilla.Domain.Entities.Contrato", b =>
                {
                    b.Navigation("Planillas");
                });

            modelBuilder.Entity("Papa.Planilla.Domain.Entities.Trabajador", b =>
                {
                    b.Navigation("Contratos");

                    b.Navigation("Planillas");
                });

            modelBuilder.Entity("Papa.Planilla.Domain.Entities.UnidadOrganica", b =>
                {
                    b.Navigation("Contratos");
                });
#pragma warning restore 612, 618
        }
    }
}
